import { Laboratory, Material, Reservation, Notification } from '@/types';

export const MOCK_LABORATORIES: Laboratory[] = [
  {
    id: '1',
    nome: 'Laboratório de Química',
    capacidade: 30,
    status: 'disponivel',
    descricao: 'Equipado com bancadas, capelas de exaustão e reagentes básicos',
  },
  {
    id: '2',
    nome: 'Laboratório de Biologia',
    capacidade: 25,
    status: 'disponivel',
    descricao: 'Microscópios, centrífugas e equipamentos de análise',
  },
  {
    id: '3',
    nome: 'Laboratório de Física',
    capacidade: 20,
    status: 'manutencao',
    descricao: 'Equipamentos de mecânica e óptica',
  },
  {
    id: '4',
    nome: 'Laboratório de Microbiologia',
    capacidade: 15,
    status: 'disponivel',
    descricao: 'Incubadoras, autoclaves e câmaras de fluxo laminar',
  },
];

export const MOCK_MATERIALS: Material[] = [
  {
    id: '1',
    nome: 'Ácido Clorídrico (HCl)',
    quantidade: 50,
    unidade: 'mL',
    validade: '2026-12-31',
    lote: 'L001',
    estoque_minimo: 20,
    categoria: 'reagente',
  },
  {
    id: '2',
    nome: 'Hidróxido de Sódio (NaOH)',
    quantidade: 15,
    unidade: 'g',
    validade: '2026-06-30',
    lote: 'L002',
    estoque_minimo: 10,
    categoria: 'reagente',
  },
  {
    id: '3',
    nome: 'Microscópio Óptico',
    quantidade: 8,
    unidade: 'unidade',
    estoque_minimo: 5,
    categoria: 'equipamento',
  },
  {
    id: '4',
    nome: 'Tubo de Ensaio',
    quantidade: 200,
    unidade: 'unidade',
    estoque_minimo: 50,
    categoria: 'vidraria',
  },
  {
    id: '5',
    nome: 'Béquer 500mL',
    quantidade: 30,
    unidade: 'unidade',
    estoque_minimo: 10,
    categoria: 'vidraria',
  },
  {
    id: '6',
    nome: 'Pipeta Graduada',
    quantidade: 5,
    unidade: 'unidade',
    estoque_minimo: 3,
    categoria: 'equipamento',
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: '1',
    laboratorio_id: '1',
    laboratorio: MOCK_LABORATORIES[0],
    docente_id: '1',
    docente: {
      id: '1',
      nome: 'Prof. João Silva',
      email: 'docente@lab.com',
      perfil: 'docente',
    },
    data: '2026-05-28',
    inicio: '10:00',
    fim: '12:00',
    disciplina: 'Química Geral',
    turma: 'A1',
    quantidade_alunos: 25,
    status: 'aprovada',
    observacoes: 'Aula prática de reações ácido-base',
    materiais: [
      {
        material_id: '1',
        material: MOCK_MATERIALS[0],
        quantidade: 20,
        disponivel: true,
      },
      {
        material_id: '4',
        material: MOCK_MATERIALS[3],
        quantidade: 30,
        disponivel: true,
      },
    ],
    data_criacao: '2026-05-27',
  },
  {
    id: '2',
    laboratorio_id: '2',
    laboratorio: MOCK_LABORATORIES[1],
    docente_id: '1',
    docente: {
      id: '1',
      nome: 'Prof. João Silva',
      email: 'docente@lab.com',
      perfil: 'docente',
    },
    data: '2026-05-29',
    inicio: '14:00',
    fim: '16:00',
    disciplina: 'Biologia Celular',
    turma: 'B2',
    quantidade_alunos: 20,
    status: 'pendente',
    observacoes: 'Observação de células ao microscópio',
    materiais: [
      {
        material_id: '3',
        material: MOCK_MATERIALS[2],
        quantidade: 5,
        disponivel: true,
      },
    ],
    data_criacao: '2026-05-27',
  },
  {
    id: '3',
    laboratorio_id: '1',
    laboratorio: MOCK_LABORATORIES[0],
    docente_id: '1',
    docente: {
      id: '1',
      nome: 'Prof. João Silva',
      email: 'docente@lab.com',
      perfil: 'docente',
    },
    data: '2026-05-30',
    inicio: '09:00',
    fim: '11:00',
    disciplina: 'Química Analítica',
    turma: 'A2',
    quantidade_alunos: 22,
    status: 'pendente',
    observacoes: 'Titulação de soluções',
    materiais: [
      {
        material_id: '1',
        material: MOCK_MATERIALS[0],
        quantidade: 15,
        disponivel: true,
      },
      {
        material_id: '6',
        material: MOCK_MATERIALS[5],
        quantidade: 3,
        disponivel: true,
      },
    ],
    data_criacao: '2026-05-27',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    usuario_id: '1',
    mensagem: 'Sua reserva foi aprovada para Química Geral - 28/05',
    tipo: 'reserva_aprovada',
    lida: false,
    data_criacao: '2026-05-27T10:30:00',
    referencia_id: '1',
  },
  {
    id: '2',
    usuario_id: '1',
    mensagem: 'Estoque de Ácido Clorídrico está baixo (15 mL)',
    tipo: 'estoque_insuficiente',
    lida: false,
    data_criacao: '2026-05-27T09:15:00',
    referencia_id: '1',
  },
  {
    id: '3',
    usuario_id: '1',
    mensagem: 'Laboratório de Física em manutenção até 30/05',
    tipo: 'manutencao',
    lida: true,
    data_criacao: '2026-05-26T14:00:00',
  },
];
